Improve test times for dt algs
LearnLib/ralib pull request #48
Opened 2023-10-05 17:40 UTC by pfg666

Now RaLambda::getHypothesis returns a regular hyp. For users wanting a DTHyp instance, there is RaLambda::getDTHyp(). I updated the test cases which required a DTHyp to pass. TestSymmetry needs to be looked at, since I had to use DTHyp there, when I am sure it should not have been necessary. That can be handled in a separate issue.

2023-10-05 18:13 UTC, kostis requested changes
I think that this PR should be complemented with a test case that shows the performance improvement (and guarantees that we do not accidentally break this again).

2023-10-06 10:02 UTC, kostis approved these changes

2023-10-06 11:26 UTC, FredrikTaquist approved these changes

2023-10-06 12:36 UTC, merged

2023-10-06 12:37 UTC, pfg666 commented
We are done here!